name: scrum_poker_analysis
description: Lint rules for scrum_poker packages and projects.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  very_good_analysis: ^5.1.0
