name: scrum_poker_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  handy_window: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  scrum_poker_analysis:
    path: ../packages/analysis

flutter:
  uses-material-design: true
